---
title: "Functional cross-sec"
author: "Li- Fang Yeo"
date: "2024-10-11"
output: html_document
---

```{r setup, include=FALSE} 
knitr::opts_chunk$set(warning = FALSE, message=FALSE) 
```
```{r, echo = FALSE}
library(magrittr)
library(RNOmni)
library(dplyr)
library(readr)
library(mia)
devtools::load_all()
```
Importing files
```{r}
#Functional pathways from metaCyc
shit.t <- readRDS("path.abund.t.rds")
shit <- readRDS("path.abund.rds")
```
```{r}
#Defining covariates for the model
vars <- list(BL_AGE = "Age",
             MEN = "Men",
             BMI = "BMI",
             PREVAL_DIAB.col_from_endpoints = "Diabetes",
             SYSTM = "Systolic blood pressure",
             BP_TREAT = "Antihypertensive medication",
             PREVAL_HFAIL_STRICT.col_from_endpoints = "Heart failure",
             PREVAL_CKD = "Prevalent CKD",
             INCIDENT_CKD = "Incident CKD",
             CKD_AGEDIFF = "CKD Agediff",
             CURR_SMOKE = "Smoking",
             PREVAL_AUTOIMMUN.col_from_endpoints = "Autoimmune disease",
             KREA_ENTS = "Creatinine",
             GFR = "Glomerulal filtration rate",
             UAC = "Urine Albumin-Creatinine Ratio",
             EAST = "Eastern Finland") 

#Importing metadata and cleaning up
#needed to match SampleID and covariates
tse <- readRDS("data/tse_gg2_MGS_FR02.rds") %>%
  tse_mutate(dplyr::across(c(MEN,
                             EAST,
                             BP_TREAT,
                             CURR_SMOKE,
                             dplyr::contains("INCIDENT"),
                             dplyr::contains("PREVAL")), as.factor)) %>% 
  tse_mutate(GFR = 0.993^round(BL_AGE) *
               dplyr::case_when(MEN == 0 & KREA_ENTS <= 62 ~ 144*(KREA_ENTS/61.9)^-0.329,
                                MEN == 0 & KREA_ENTS >  62 ~ 144*(KREA_ENTS/61.9)^-1.209,
                                MEN == 1 & KREA_ENTS <= 80 ~ 141*(KREA_ENTS/79.6)^-0.411,
                                MEN == 1 & KREA_ENTS >  80 ~ 141*(KREA_ENTS/79.6)^-1.209)) %>%
  tse_mutate(UAC = U_ALB/U_KREA) %>% 
  tse_filter(GRAVID %in% c(1, NA), BL_USE_RX_J01_1mo %in% c(0, NA)) %>%
  tse_filter(dplyr::if_all(dplyr::one_of(names(vars) %difference% "UAC"), not_na)) %>%
  tse_select(names(vars))
```
Prevalence filtering
```{r}
#You will get a dataframe of prevalent pathways
#poo needs to have samples as row, pathways as column
shit.10 <- shit.t %>% 
  select(-1) %>%
  #mutate to 1 for everything > 0.0000000001
  mutate(across(everything(), ~ . > 10^-10)) %>%
  #get proportion
  summarize(across(everything(), mean)) %>%
  tidyr::gather(Pathway,prevalence) %>%
  #filter for pathways that are prevalent in 10%
  dplyr::filter(prevalence >0.1) 

# filtered to only prevalent pathways
hi <- shit.10 %>% 
  select(-2) %>%
  dplyr::inner_join(shit, by="Pathway" ) %>%
  t() %>%
  as.data.frame()

#take first row as colname
colnames(hi) <- hi[1,]
#remove extra row
hi <- hi[-1, ] 
#change from character to numeric
hi <- hi %>% mutate_if(is.character, as.numeric) %>%
  tibble::rownames_to_column("Barcode") 
```
Reduce to dichotomous variables (absence / presence)
```{r}
#Get df that has prevalence filtered pathway
#Dichotomise
poo_dicho <- hi %>% 
  mutate(across(where(is.numeric), ~ ifelse(. > 0, 1, 0)))
```
join functional data to metadata
```{r}
#Match samples with (filtered) tse
a <- as.data.frame(colData(tse))%>%
  tibble::rownames_to_column("Barcode")
  
rm(tse)

df <- dplyr::inner_join(poo_dicho, a, by = "Barcode")
```
Linear model + covariates
```{r}
#Creatinine
lm_crea_partial <-  purrr::partial(lm,
                                  formula = KREA_ENTS ~
                                    term + BL_AGE + MEN + BMI +
                                    PREVAL_DIAB.col_from_endpoints + SYSTM + BP_TREAT +
                                    PREVAL_HFAIL_STRICT.col_from_endpoints + CURR_SMOKE +
                                    PREVAL_AUTOIMMUN.col_from_endpoints)
#UAC
lm_uac_partial <-  purrr::partial(lm,
                                  formula = log(UAC) ~
                                    term + BL_AGE + MEN + BMI +
                                    PREVAL_DIAB.col_from_endpoints + SYSTM + BP_TREAT +
                                    PREVAL_HFAIL_STRICT.col_from_endpoints + CURR_SMOKE +
                                    PREVAL_AUTOIMMUN.col_from_endpoints)
```
```{r}
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_crea_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model for MetaCyc pathways")
```
```{r}
#UAC
lm_uac_partial <-  purrr::partial(lm,
                                  formula = log(UAC) ~
                                    term + BL_AGE + MEN + BMI +
                                    PREVAL_DIAB.col_from_endpoints + SYSTM + BP_TREAT +
                                    PREVAL_HFAIL_STRICT.col_from_endpoints + CURR_SMOKE +
                                    PREVAL_AUTOIMMUN.col_from_endpoints)
```
```{r}
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_uac_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model for MetaCyc pathways")
```
Tranform to inverse_rank
```{r}
# Define the transformation function
transform_column <- function(x) {
  qnorm((rank(x, na.last = "keep") - 0.5) / sum(!is.na(x)))
}

# Apply the transformation to all columns
poo_rank <- hi
poo_rank[, -1] <- lapply(hi[, -1], transform_column)
```
Data wrangling to join functional data to metadata
```{r}
#Here you will have the correct number of samples
df <- dplyr::inner_join(poo_rank, a, by = "Barcode")

##Linear model
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_crea_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model for MetaCyc pathways")
```
```{r}
#UAC
lm_uac_partial <-  purrr::partial(lm,
                                  formula = log(UAC) ~
                                    term + BL_AGE + MEN + BMI +
                                    PREVAL_DIAB.col_from_endpoints + SYSTM + BP_TREAT +
                                    PREVAL_HFAIL_STRICT.col_from_endpoints + CURR_SMOKE +
                                    PREVAL_AUTOIMMUN.col_from_endpoints)
```
```{r}
#Take the column names from Pathway in shit dataframe as a list and mutate
try <- shit.10 %>% dplyr::select(Pathway) %>% 
  dplyr::mutate(results = purrr::map(Pathway, ~lm_uac_partial(data = df %>% dplyr::rename(term = .x)), .progress = TRUE))

try%>% 
  dplyr::filter(!is.na(results)) %>%
  dplyr::mutate(results = purrr::map(results, ~broom::tidy(.x, exponentiate = TRUE, conf.int = TRUE)))  %>%
  tidyr::unnest(results) %>%
  dplyr::filter(term == "term") %>%
  dplyr::mutate(qval_fdr = p.adjust(p.value, method = "BH")) %>%
  dplyr::arrange(p.value) %>%
  dplyr::mutate_if(is.numeric, ~round(.x, digits = 4)) %>%
  DT::datatable(caption = "Linear model for MetaCyc pathways")
```